-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.analytical_sales
(
    transaction_id integer NOT NULL,
    product_category character varying(30) COLLATE pg_catalog."default",
    units_sold integer,
    total_revenue numeric(8, 2),
    CONSTRAINT analytical_sales_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.checkout_registers
(
    register_id integer NOT NULL,
    hardware_model character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT checkout_registers_pkey PRIMARY KEY (register_id)
);

CREATE TABLE IF NOT EXISTS public.corporate_stores
(
    store_id integer NOT NULL,
    city_location character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT corporate_stores_pkey PRIMARY KEY (store_id)
);

CREATE TABLE IF NOT EXISTS public.product_inventory
(
    product_id integer,
    product_name character varying(100) COLLATE pg_catalog."default",
    product_sku character varying(20) COLLATE pg_catalog."default",
    wholesale_cost numeric(8, 2),
    date_stocked date
);

ALTER TABLE IF EXISTS public.corporate_stores
    ADD FOREIGN KEY (store_id)
    REFERENCES public.checkout_registers (register_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;